/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.funcionario;

import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdbc.FuncionarioJdbc;
import jdbc.Jdbc;
import modelo.Funcionario;

/**
 *
 * @author EstiRasta
 */
public class GUI_ModificarFuncionario extends javax.swing.JInternalFrame {
    private Funcionario f1 = new Funcionario();
    /**
     * Creates new form GUI_EditarFuncionario
     */
    public GUI_ModificarFuncionario() {
        initComponents();
        groupBtnSexo.add(rBtn1);
        groupBtnSexo.add(rBtn2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        rBtn1 = new javax.swing.JRadioButton();
        rBtn2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRol = new javax.swing.JComboBox<String>();
        txtTelefono = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtFechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtBuscarById = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        label3 = new java.awt.Label();
        lblNumId = new java.awt.Label();

        setClosable(true);
        setTitle("Editar Funcionario");
        setMinimumSize(new java.awt.Dimension(879, 490));
        setPreferredSize(new java.awt.Dimension(879, 490));
        getContentPane().setLayout(null);

        jLabel1.setText("Identificacion: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 150, 120, 14);

        jLabel2.setText("Segundo Apellido: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 310, 140, 14);

        jLabel3.setText("Primier Apellido: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 270, 130, 14);

        jLabel4.setText("Primer Nombre: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 130, 14);

        jLabel5.setText("Segundo Nombre: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 230, 140, 14);

        jLabel6.setText("Fecha De Nacimiento: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 350, 160, 14);

        jLabel7.setText("Correo Electronico: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 200, 160, 14);

        jLabel8.setText("Sexo: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 160, 90, 14);

        txtIdentificacion.setName("txtIdentificacionF"); // NOI18N
        getContentPane().add(txtIdentificacion);
        txtIdentificacion.setBounds(210, 150, 178, 20);

        txtNombre2.setName("txtSegundoNombreF"); // NOI18N
        getContentPane().add(txtNombre2);
        txtNombre2.setBounds(210, 230, 178, 20);

        txtNombre1.setName("txtPrimerNombreF"); // NOI18N
        getContentPane().add(txtNombre1);
        txtNombre1.setBounds(210, 190, 178, 20);

        txtApellido1.setName("txtPrimerApellidoF"); // NOI18N
        getContentPane().add(txtApellido1);
        txtApellido1.setBounds(210, 270, 178, 20);

        txtApellido2.setName("txtSegundoApellidoF"); // NOI18N
        getContentPane().add(txtApellido2);
        txtApellido2.setBounds(210, 310, 178, 20);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(620, 190, 178, 20);

        rBtn1.setText("Hombre");
        getContentPane().add(rBtn1);
        rBtn1.setBounds(620, 150, 100, 23);

        rBtn2.setText("Mujer");
        getContentPane().add(rBtn2);
        rBtn2.setBounds(720, 150, 90, 23);

        jLabel10.setText("Telefono: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 240, 110, 14);

        jLabel11.setText("Contraseña");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(450, 310, 120, 14);

        jLabel12.setText("Cargo: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 270, 100, 14);

        txtRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administardor", "Auxiliar", "Coordinador" }));
        getContentPane().add(txtRol);
        txtRol.setBounds(620, 270, 178, 20);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(620, 230, 178, 20);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(620, 310, 178, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 400, 120, 40);

        jButton2.setText("Volver");
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 400, 120, 40);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 400, 110, 40);
        getContentPane().add(txtFechaNacimiento);
        txtFechaNacimiento.setBounds(210, 350, 180, 20);

        txtBuscarById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarByIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscarById);
        txtBuscarById.setBounds(570, 110, 180, 20);

        button1.setLabel("Buscar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(760, 110, 70, 24);

        label3.setText("Busqueda por Identificacion:");
        getContentPane().add(label3);
        label3.setBounds(570, 80, 190, 20);
        getContentPane().add(lblNumId);
        lblNumId.setBounds(90, 90, 4, 20);
        lblNumId.getAccessibleContext().setAccessibleName("lblNumid");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sexo = "";

        if (rBtn1.isSelected()) {
            sexo = "Masculino";
        } else if (rBtn2.isSelected()) {
            sexo = "Femenido";
        }

        char[] arrayC = txtPassword.getPassword();
        String pass = new String(arrayC);

        f1.setApellido1(txtApellido1.getText().trim());
        f1.setApellido2(txtApellido2.getText().trim());
        f1.setCorreo(txtCorreo.getText().trim());
        f1.setFechaNacimiento(new Date(txtFechaNacimiento.getDate().getTime()));
        f1.setIdentificacion(txtIdentificacion.getText().trim());
        f1.setNombre1(txtNombre1.getText().trim());
        f1.setNombre2(txtNombre2.getText().trim());
        f1.setPassword(pass);
        f1.setSexo(sexo);
        f1.setTelefono(txtTelefono.getText().trim());
        f1.setRol(txtRol.getSelectedItem().toString());

        Jdbc cx = new Jdbc();
        FuncionarioJdbc fjdbc = new FuncionarioJdbc();
        try {
            cx.conectarme();
            fjdbc.setCon(cx.getCon());
            fjdbc.updateFuncionario(f1);

        } catch (SQLException ex) {
            Logger.getLogger(GUI_ModificarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        Jdbc cx = new Jdbc();
        FuncionarioJdbc fjdbc = new FuncionarioJdbc();
        try {
            cx.conectarme();
            fjdbc.setCon(cx.getCon());           
            
            f1 = fjdbc.getFuncionario(txtBuscarById.getText().trim());            
            txtApellido1.setText(f1.getApellido1());
            txtApellido2.setText(f1.getApellido2());
            txtCorreo.setText(f1.getCorreo());
            txtFechaNacimiento.setDate(new Date(f1.getFechaNacimiento().getTime()));
            txtIdentificacion.setText(f1.getIdentificacion());
            txtNombre1.setText(f1.getNombre1());
            txtNombre2.setText(f1.getNombre2());
            txtTelefono.setText(f1.getTelefono());
            txtRol.setSelectedItem(f1.getRol());
            txtPassword.setText(f1.getPassword());
            
            if ("Masculino".equals(f1.getSexo())) {
                rBtn1.setSelected(true);
            }else {
                rBtn2.setSelected(true);
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(GUI_ModificarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void txtBuscarByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarByIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarByIdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.ButtonGroup groupBtnSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Label label3;
    private java.awt.Label lblNumId;
    private javax.swing.JRadioButton rBtn1;
    private javax.swing.JRadioButton rBtn2;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtBuscarById;
    private javax.swing.JTextField txtCorreo;
    private com.toedter.calendar.JDateChooser txtFechaNacimiento;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JComboBox<String> txtRol;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
