/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.funcionario;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import jdbc.Jdbc;
import jdbc.FuncionarioJdbc;
import modelo.Funcionario;
import vistas.Fondo;
import vistas.GUI_Principal;

/**
 *
 * @author Usuario
 */
public class GUI_Crear_Funcionario extends javax.swing.JInternalFrame {
  

    /**
     * Creates new form GUI_Crear_Funcionario
     */
    public GUI_Crear_Funcionario() {
        initComponents();
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
        lbl5.setVisible(false);
        lbl6.setVisible(false);
        lbl7.setVisible(false);
        lbl8.setVisible(false);
        lbl9.setVisible(false);
        lbl10.setVisible(false);
        groupSexoBtn.add(rBtn1);
        groupSexoBtn.add(rBtn2);
        cargarImagen(jdp4,foto1);
        ocultarBarraTitulo();
        
    }
    
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
private Dimension dimBarra = null; 
public void ocultarBarraTitulo()
{ 
Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
dimBarra = Barra.getPreferredSize(); 
Barra.setSize(0,0); 
Barra.setPreferredSize(new Dimension(0,0)); 
repaint(); 
}
  public InputStream foto1=this.getClass().getResourceAsStream("/imagenes/bl.jpg");
            public  void cargarImagen(javax.swing.JDesktopPane jDeskp,InputStream fileImagen)
    {   
        try{   
            BufferedImage image = ImageIO.read(fileImagen);        
              jDeskp.setBorder(new Fondo(image)); }
        catch (Exception e){   System.out.println("Imagen no disponible");   }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSexoBtn = new javax.swing.ButtonGroup();
        jdp4 = new javax.swing.JDesktopPane();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFechaNacimiento = new com.toedter.calendar.JDateChooser();
        rBtn1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmbRol = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        rBtn2 = new javax.swing.JRadioButton();
        btnCerrarVistaCrearFuncionario = new javax.swing.JButton();
        btnRegistrarFuncionario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);
        setTitle("Crear Funcionario");
        setPreferredSize(new java.awt.Dimension(792, 437));
        setVisible(true);
        getContentPane().setLayout(null);

        jdp4.setBackground(new java.awt.Color(255, 255, 255));

        txtIdentificacion.setName("txtIdentificacionF"); // NOI18N
        jdp4.add(txtIdentificacion);
        txtIdentificacion.setBounds(190, 130, 178, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Identificacion: ");
        jdp4.add(jLabel1);
        jLabel1.setBounds(20, 130, 80, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Primer Nombre: ");
        jdp4.add(jLabel4);
        jLabel4.setBounds(20, 170, 80, 14);

        txtNombre1.setName("txtPrimerNombreF"); // NOI18N
        jdp4.add(txtNombre1);
        txtNombre1.setBounds(190, 170, 178, 20);

        txtNombre2.setName("txtSegundoNombreF"); // NOI18N
        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });
        jdp4.add(txtNombre2);
        txtNombre2.setBounds(190, 210, 178, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Segundo Nombre: ");
        jdp4.add(jLabel5);
        jLabel5.setBounds(20, 210, 90, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Primier Apellido: ");
        jdp4.add(jLabel3);
        jLabel3.setBounds(20, 250, 90, 14);

        txtApellido1.setName("txtPrimerApellidoF"); // NOI18N
        jdp4.add(txtApellido1);
        txtApellido1.setBounds(190, 250, 178, 20);

        txtApellido2.setName("txtSegundoApellidoF"); // NOI18N
        jdp4.add(txtApellido2);
        txtApellido2.setBounds(190, 290, 178, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Segundo Apellido: ");
        jdp4.add(jLabel2);
        jLabel2.setBounds(20, 290, 100, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Fecha De Nacimiento: ");
        jdp4.add(jLabel6);
        jLabel6.setBounds(20, 330, 110, 14);
        jdp4.add(txtFechaNacimiento);
        txtFechaNacimiento.setBounds(190, 330, 180, 20);

        rBtn1.setText("Masculino");
        jdp4.add(rBtn1);
        rBtn1.setBounds(580, 120, 90, 23);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Sexo: ");
        jdp4.add(jLabel8);
        jLabel8.setBounds(410, 130, 30, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Correo Electronico: ");
        jdp4.add(jLabel7);
        jLabel7.setBounds(410, 170, 100, 14);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Telefono: ");
        jdp4.add(jLabel10);
        jLabel10.setBounds(410, 210, 60, 14);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Cargo: ");
        jdp4.add(jLabel12);
        jLabel12.setBounds(410, 250, 40, 14);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Contraseña");
        jdp4.add(jLabel11);
        jLabel11.setBounds(410, 290, 70, 14);
        jdp4.add(txtPassword);
        txtPassword.setBounds(580, 290, 178, 20);

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administardor", "Auxiliar", "Coordinador" }));
        jdp4.add(cmbRol);
        cmbRol.setBounds(580, 250, 178, 20);
        jdp4.add(txtTelefono);
        txtTelefono.setBounds(580, 210, 178, 20);
        jdp4.add(txtCorreo);
        txtCorreo.setBounds(580, 170, 178, 20);

        rBtn2.setText("Femenino");
        jdp4.add(rBtn2);
        rBtn2.setBounds(670, 120, 90, 23);

        btnCerrarVistaCrearFuncionario.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarVistaCrearFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCerrarVistaCrearFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarVistaCrearFuncionario.setText("CERRAR");
        btnCerrarVistaCrearFuncionario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnCerrarVistaCrearFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarVistaCrearFuncionarioActionPerformed(evt);
            }
        });
        jdp4.add(btnCerrarVistaCrearFuncionario);
        btnCerrarVistaCrearFuncionario.setBounds(500, 410, 110, 30);

        btnRegistrarFuncionario.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegistrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarFuncionario.setText("REGISTRAR");
        btnRegistrarFuncionario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnRegistrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFuncionarioActionPerformed(evt);
            }
        });
        jdp4.add(btnRegistrarFuncionario);
        btnRegistrarFuncionario.setBounds(290, 410, 120, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("CREAR FUNCIONARIO");
        jdp4.add(jLabel9);
        jLabel9.setBounds(330, 60, 220, 14);

        lbl10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(255, 0, 0));
        lbl10.setText("*");
        jdp4.add(lbl10);
        lbl10.setBounds(570, 294, 20, 20);

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 0, 0));
        lbl1.setText("*");
        jdp4.add(lbl1);
        lbl1.setBounds(180, 140, 10, 10);

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 0, 0));
        lbl3.setText("*");
        jdp4.add(lbl3);
        lbl3.setBounds(180, 260, 20, 10);

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 0, 0));
        lbl2.setText("*");
        jdp4.add(lbl2);
        lbl2.setBounds(180, 180, 10, 10);

        lbl6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 0, 0));
        lbl6.setText("*");
        jdp4.add(lbl6);
        lbl6.setBounds(570, 130, 20, 14);

        lbl4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 0, 0));
        lbl4.setText("*");
        jdp4.add(lbl4);
        lbl4.setBounds(180, 300, 20, 10);

        lbl5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 0, 0));
        lbl5.setText("*");
        jdp4.add(lbl5);
        lbl5.setBounds(180, 340, 20, 10);

        lbl7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(255, 0, 0));
        lbl7.setText("*");
        jdp4.add(lbl7);
        lbl7.setBounds(570, 180, 20, 10);

        lbl8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 0, 0));
        lbl8.setText("*");
        jdp4.add(lbl8);
        lbl8.setBounds(570, 210, 10, 20);

        lbl9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(255, 0, 0));
        lbl9.setText("*");
        jdp4.add(lbl9);
        lbl9.setBounds(570, 254, 20, 20);

        getContentPane().add(jdp4);
        jdp4.setBounds(-10, -30, 850, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFuncionarioActionPerformed
        // TODO add your handling code here:
        String sexo = "";     
            
        if (rBtn1.isSelected()) {
            sexo = "Masculino";
        } else if (rBtn2.isSelected()) {
            sexo = "Femenido";
        }else{
            lbl6.setVisible(true);
            JOptionPane.showMessageDialog(null, "Seleccione el sexo", sexo, (2));
        }
        
        
//        if(txtPassword.getPass().equals("")){
//            lbl10.setVisible(true);
//        }
        if(txtIdentificacion.getText().trim().equals("")){
            lbl1.setVisible(true);
            
        }
        
        char[] arrayPass = txtPassword.getPassword();
        String password = new String(arrayPass);
        if (password.equals("")) {
            lbl10.setVisible(true);
        }
        if(txtNombre1.getText().trim().equals("")){
            lbl2.setVisible(true);
           
        }
        if(txtApellido1.getText().trim().equals("")){
            lbl3.setVisible(true);
        }
        if(txtApellido2.getText().trim().equals("")){
            lbl4.setVisible(true);
        }
        if(txtFechaNacimiento.getDateFormatString().trim().equals("")){
            lbl5.setVisible(true);
        }
        if(txtCorreo.getText().equals("")){
            lbl7.setVisible(true);
        }
        if(txtTelefono.getText().trim().equals("")){
            lbl8.setVisible(true);
            JOptionPane.showMessageDialog(this, "No deje campos vacios\nLos campos con (*) son obligatorios");
            return;
        }
        
        System.out.println("date: "+ txtFechaNacimiento.getDate());

        char[] arrayC = txtPassword.getPassword();
        String pass = new String(arrayC);

        Funcionario f1 = new Funcionario();
        f1.setApellido1(txtApellido1.getText().trim());
        f1.setApellido2(txtApellido2.getText().trim());
        f1.setCorreo(txtCorreo.getText().trim());
        f1.setFechaNacimiento(txtFechaNacimiento.getDate());
        f1.setIdentificacion(txtIdentificacion.getText().trim());
        f1.setNombre1(txtNombre1.getText().trim());
        f1.setNombre2(txtNombre2.getText().trim());
        f1.setPassword(pass);
        f1.setSexo(sexo);
        f1.setTelefono(txtTelefono.getText().trim());
        f1.setRol(cmbRol.getSelectedItem().toString().trim());

        Jdbc cx = new Jdbc();
        FuncionarioJdbc fjdbc = new FuncionarioJdbc();
        try {
            cx.conectarme();
            fjdbc.setCon(cx.getCon());
            fjdbc.saveFuncionario(f1);

        } catch (SQLException ex) {
            Logger.getLogger(GUI_Crear_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarFuncionarioActionPerformed

    private void btnCerrarVistaCrearFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarVistaCrearFuncionarioActionPerformed
                  // GUI_Principal.labeltitulo.setVisible(true);
                  //  GUI_Principal.labelsubt.setVisible(true);        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarVistaCrearFuncionarioActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarVistaCrearFuncionario;
    private javax.swing.JButton btnRegistrarFuncionario;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.ButtonGroup groupSexoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDesktopPane jdp4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JRadioButton rBtn1;
    private javax.swing.JRadioButton rBtn2;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCorreo;
    private com.toedter.calendar.JDateChooser txtFechaNacimiento;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
