/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.prestamo;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdbc.Jdbc;
import jdbc.MaterialJdbc;
import jdbc.PrestamoJdbc;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author EstiRasta
 */
public class GUI_DevolucionPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_DevolucionPrestamo
     */
    public GUI_DevolucionPrestamo() {
        initComponents();

        PanamaHitek_Arduino ino = new PanamaHitek_Arduino();
        SerialPortEventListener listener;
        listener = (SerialPortEvent serialPortEvent) -> {

            try {
                if (ino.isMessageAvailable()) {
                    lblCodigo.setText(ino.printMessage());
                    ino.sendData("v");
                    ino.killArduinoConnection();
                }
            } catch (SerialPortException | ArduinoException ex) {
                Logger.getLogger(GUI_Crear_Prestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }; //Si se recibe algun dato en el puerto serie, se ejecuta el siguiente metodo
        try {
            ino.arduinoRXTX("COM5", 9600, listener);

        } catch (ArduinoException ex) {
            Logger.getLogger(GUI_DevolucionPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDevolver = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        label2 = new java.awt.Label();
        lblCodigo = new java.awt.Label();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Devolucion de Material");
        setMinimumSize(new java.awt.Dimension(837, 518));
        setName(""); // NOI18N
        getContentPane().setLayout(null);

        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnDevolver);
        btnDevolver.setBounds(182, 343, 152, 52);

        btnCerrar.setText("Cerrar");
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(459, 343, 152, 52);

        label2.setText("Por favor Escanee el libro para la devolucion!");
        getContentPane().add(label2);
        label2.setBounds(223, 49, 285, 45);

        lblCodigo.setText("9F 4D AC 89");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(310, 90, 194, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
        if (!"".equals(lblCodigo.getText())) {
            Jdbc cx = new Jdbc();
            MaterialJdbc mjdbc = new MaterialJdbc();
            PrestamoJdbc pjdbc = new PrestamoJdbc();

            try {
                cx.conectarme();
                mjdbc.setCon(cx.getCon());
                mjdbc.updateDisponible(lblCodigo.getText().trim(), true);
                
                 java.util.Date now = new java.util.Date();
                pjdbc.setCon(cx.getCon());
                pjdbc.updatePrestamo(new Timestamp(now.getTime()), lblCodigo.getText().trim());

            } catch (SQLException ex) {
                Logger.getLogger(GUI_DevolucionPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnDevolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDevolver;
    private java.awt.Label label2;
    private java.awt.Label lblCodigo;
    // End of variables declaration//GEN-END:variables
}
