/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class GUI_Crear_Prestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_Crear_Prestamo
     */
    public GUI_Crear_Prestamo() {
        initComponents();
        ImageIcon imagen = new ImageIcon ("src/imagenes/Prestamo.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblFondo.getWidth(),lblFondo.getHeight(),Image.SCALE_DEFAULT));
        lblFondo.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Crear Prestamo");
        getContentPane().setLayout(null);

        jLabel1.setText("Material Bibliografico a Prestar: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 55, 152, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(283, 52, 216, 20);

        jLabel2.setText("Persona Quin Realiza el Prestamo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 93, 164, 14);

        jLabel3.setText("Fecha del prestamo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 131, 98, 14);

        jLabel4.setText("Fecha Limite De Devolucion:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 160, 134, 14);

        jLabel5.setText("Fecha De Devolucion Real:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(43, 198, 128, 14);

        jLabel6.setText("Tipo De Prestamo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(43, 236, 88, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(283, 90, 216, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(283, 157, 216, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(283, 195, 216, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(283, 128, 216, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(283, 233, 216, 20);

        jButton1.setText("Ejecutar Prestamo");
        getContentPane().add(jButton1);
        jButton1.setBounds(71, 290, 140, 23);

        jButton2.setText("Volver");
        getContentPane().add(jButton2);
        jButton2.setBounds(253, 288, 80, 23);

        jButton3.setText("Salir");
        getContentPane().add(jButton3);
        jButton3.setBounds(382, 288, 90, 23);
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 540, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
