/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Usuario
 */
public class GUI_Crear_Funcionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_Crear_Funcionario
     */
    public GUI_Crear_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Craer Funcionaerio");
        setVisible(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Identificacion: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(19, 34, 71, 14);

        jLabel2.setText("Segundo Apellido: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(19, 191, 89, 14);

        jLabel3.setText("Primier Apellido: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(19, 153, 79, 14);

        jLabel4.setText("Primer Nombre: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(19, 74, 77, 14);

        jLabel5.setText("Segundo Nombre: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(19, 112, 89, 14);

        jLabel6.setText("Fecha De Nacimiento: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(19, 229, 107, 14);

        jLabel7.setText("Correo Electronico: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(396, 77, 95, 14);

        jLabel8.setText("Sexo: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(396, 34, 31, 14);

        jLabel9.setText("Direccion De Residencia: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(396, 115, 120, 14);

        jTextField1.setName("txtIdentificacionF"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(164, 31, 178, 20);

        jTextField2.setName("txtSegundoNombreF"); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(164, 112, 178, 20);

        jTextField3.setName("txtPrimerNombreF"); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(164, 71, 178, 20);

        jTextField4.setName("txtPrimerApellidoF"); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(164, 150, 178, 20);

        jTextField5.setName("txtSegundoApellidoF"); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(164, 188, 178, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(567, 74, 178, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(567, 112, 178, 20);

        jRadioButton1.setText("Hombre");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(567, 30, 63, 23);

        jRadioButton2.setText("Mujer");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(648, 30, 53, 23);

        jLabel10.setText("Telefono: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(396, 153, 49, 14);

        jLabel11.setText("Contraseña");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(396, 229, 56, 14);

        jLabel12.setText("Cargo: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(396, 191, 36, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administardor", "Auxiliar", "Coordinador" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(567, 188, 178, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(567, 150, 178, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(567, 226, 178, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(187, 315, 77, 23);

        jButton2.setText("Volver");
        getContentPane().add(jButton2);
        jButton2.setBounds(416, 315, 77, 23);

        jButton3.setText("Salir");
        getContentPane().add(jButton3);
        jButton3.setBounds(629, 315, 77, 23);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(170, 230, 170, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administrativo.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 790, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
