/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import vistas.prestamo.GUI_Crear_Prestamo;
import vistas.usuario.GUI_Crear_Usuario;
import vistas.funcionario.GUI_Crear_Funcionario;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import jdbc.FuncionarioJdbc;
import vistas.funcionario.GUI_ModificarFuncionario;
import vistas.funcionario.GUI_ListarFuncionarios;
import vistas.material.GUI_Modificar_Material_Bibliografico;
import vistas.usuario.GUI_ListarUsuarios;
import vistas.usuario.GUI_Modificar_Usuario;
import jdbc.Jdbc;
import jdbc.UsuarioJdbc;
import modelo.Funcionario;
import modelo.Usuario;
import vistas.material.GUI_Crear_Material_Bibliografico;
import vistas.material.GUI_ListarMateriales;
import vistas.prestamo.GUI_DevolucionPrestamo;
import vistas.prestamo.GUI_ListarPrestamos;

/**
 *
 * @author Usuario
 */
public class GUI_Principal extends javax.swing.JFrame {

    public InputStream foto1 = this.getClass().getResourceAsStream("/imagenes/bliii1.jpg");
    public InputStream foto2 = this.getClass().getResourceAsStream("/imagenes/bl.jpg");
    public InputStream foto3 = this.getClass().getResourceAsStream("/imagenes/invi.jpg");
    public InputStream foto4 = this.getClass().getResourceAsStream("/imagenes/fondo6.jpg");

    private Funcionario dataF1 = new Funcionario();
    private Usuario dataU1 = new Usuario();

    /**
     * Creates new form Menu
     */
    public GUI_Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jMenu1.setVisible(false);
        jMenu2.setVisible(false);
        jMenu3.setVisible(false);
        jMenu4.setVisible(false);
        jMenu5.setVisible(false);
        jMenu6.setVisible(false);
        cargarImagen(jdp, foto1);
        cargarImagen(jdp2, foto2);
        cargarImagen(jdp3, foto3);
        jMenuBar1.setVisible(false);
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
    }

    public void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new Fondo(image));
        } catch (Exception e) {
            System.out.println("Imagen  no  disponible");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jdp = new javax.swing.JDesktopPane();
        jdp2 = new javax.swing.JDesktopPane();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JComboBox<>();
        btnIniciarSecion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jdp3 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        labelsubt = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 494));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jdp.setBackground(new java.awt.Color(255, 255, 255));

        jdp2.setBackground(new java.awt.Color(204, 204, 204));
        jdp2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jdp2.add(txtUsuario);
        txtUsuario.setBounds(21, 110, 397, 26);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("USUARIO");
        jdp2.add(jLabel1);
        jLabel1.setBounds(21, 78, 87, 26);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("CONTRASEÑA:");
        jdp2.add(jLabel2);
        jLabel2.setBounds(21, 154, 124, 26);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jdp2.add(txtPassword);
        txtPassword.setBounds(21, 186, 397, 26);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("TIPO");
        jdp2.add(jLabel3);
        jLabel3.setBounds(21, 235, 42, 26);

        txtTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "Usuario" }));
        txtTipo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jdp2.add(txtTipo);
        txtTipo.setBounds(21, 267, 397, 26);

        btnIniciarSecion.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciarSecion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnIniciarSecion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSecion.setText("LOGIN");
        btnIniciarSecion.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnIniciarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSecionActionPerformed(evt);
            }
        });
        jdp2.add(btnIniciarSecion);
        btnIniciarSecion.setBounds(21, 352, 137, 41);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setText("Login");
        jdp2.add(jLabel4);
        jLabel4.setBounds(21, 14, 363, 42);

        jdp3.setBackground(new java.awt.Color(153, 153, 153));
        jdp3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jdp3.setAlignmentX(5.0F);
        jdp3.setAlignmentY(5.0F);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("  Welcome");
        jdp3.add(jLabel5);
        jLabel5.setBounds(13, 169, 363, 56);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Your library system");
        jdp3.add(jLabel6);
        jLabel6.setBounds(23, 231, 363, 30);

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu-close-x.png"))); // NOI18N
        btnCerrar.setText("EXIT");
        btnCerrar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnCerrar.setPreferredSize(new java.awt.Dimension(37, 37));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        labelsubt.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N

        labeltitulo.setFont(new java.awt.Font("Times New Roman", 0, 100)); // NOI18N
        labeltitulo.setText("Unicolombo Library System");

        jdp.setLayer(jdp2, javax.swing.JLayeredPane.DRAG_LAYER);
        jdp.setLayer(jdp3, javax.swing.JLayeredPane.DRAG_LAYER);
        jdp.setLayer(btnCerrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp.setLayer(labelsubt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp.setLayer(labeltitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpLayout = new javax.swing.GroupLayout(jdp);
        jdp.setLayout(jdpLayout);
        jdpLayout.setHorizontalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpLayout.createSequentialGroup()
                .addGroup(jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpLayout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(labelsubt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdpLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdp3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jdpLayout.createSequentialGroup()
                                        .addGap(410, 410, 410)
                                        .addComponent(jdp2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jdpLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(labeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jdpLayout.setVerticalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpLayout.createSequentialGroup()
                .addGroup(jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelsubt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdp3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdp2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jdp);
        jdp.setBounds(0, 0, 1460, 840);

        jMenu6.setText("jMenu6");

        jMenuItem8.setText("Mis prestamos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem12.setText("Delvolver material");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem17.setText("Cerrar sesion");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem17);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("Prestamo");

        jMenuItem13.setText("Crear Prestamo");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem15.setText("Listar Prestamo");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Material Biliografico");

        jMenuItem9.setText("Crear Material Biliografico");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Modificar Material Biliografico");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Listar Materiales Biliograficos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Usuario");

        jMenuItem6.setText("Crear Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem5.setText("Modificar Usuario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Listar Usuarios");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Salir");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Confirmar salida");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Funcionario");
        jMenu1.setName(""); // NOI18N

        jMenuItem1.setText("Crear Funcionario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar Funcionario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Listar Funcionarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        // TODO add your handling code here:
        GUI_Modificar_Usuario mu = new GUI_Modificar_Usuario();
        jdp.add(mu);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = mu.getSize();
        mu.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        mu.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        GUI_Crear_Funcionario cf = new GUI_Crear_Funcionario();
        jdp.add(cf);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = cf.getSize();
        cf.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        GUI_Crear_Usuario cu = new GUI_Crear_Usuario();
        jdp.add(cu);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = cu.getSize();
        cu.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        cu.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        GUI_Crear_Material_Bibliografico cmb = new GUI_Crear_Material_Bibliografico();
        jdp.add(cmb);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = cmb.getSize();
        cmb.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        cmb.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        
        
        GUI_Crear_Prestamo cp = new GUI_Crear_Prestamo();
        cp.u1 = dataU1;
        jdp.add(cp);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = cp.getSize();
        cp.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        GUI_ModificarFuncionario mf = new GUI_ModificarFuncionario();
        jdp.add(mf);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = mf.getSize();
        mf.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        mf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);        // TODO add your handling code here:
        GUI_ListarFuncionarios lf = new GUI_ListarFuncionarios();
        jdp.add(lf);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = lf.getSize();
        lf.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        
        GUI_ListarUsuarios lu = new GUI_ListarUsuarios();
        jdp.add(lu);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = lu.getSize();
        lu.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        lu.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);        // TODO add your handling code here:
        GUI_Modificar_Material_Bibliografico mmb = new GUI_Modificar_Material_Bibliografico();
        jdp.add(mmb);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = mmb.getSize();
        mmb.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        mmb.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        dataF1 = null;
        dataU1 = null;

        jMenuBar1.setVisible(false);
        jMenu4.setVisible(false);
        jMenu6.setVisible(false);
        jdp2.setVisible(true);
        jdp3.setVisible(true);
        btnCerrar.setVisible(true);
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        // TODO add your handling code here:
        GUI_ListarMateriales lm = new GUI_ListarMateriales();
        jdp.add(lm);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = lm.getSize();
        lm.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        lm.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void btnIniciarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSecionActionPerformed
        
        if (txtUsuario.getText().trim().equals("") || txtPassword.getPassword().toString().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor no deje campos vacios", "Error", (0));
        } else {
            if (txtTipo.getSelectedItem() == "Funcionario") {

                Jdbc cx = new Jdbc();
                FuncionarioJdbc fjdbc = new FuncionarioJdbc();
                try {
                    cx.conectarme();
                    fjdbc.setCon(cx.getCon());

                    char[] arrayC = txtPassword.getPassword();
                    String pass = new String(arrayC);

                    dataF1 = fjdbc.Login(txtUsuario.getText().trim(), pass);

                    if (dataF1.getIdentificacion() != null) {
                        txtUsuario.setText("");
                        txtPassword.setText("");

                        JOptionPane.showMessageDialog(null, "Welcome " + dataF1.getNombre1() + " " + dataF1.getApellido1());
                        jMenu6.setText(dataF1.getNombre1() + " " + dataF1.getApellido1());
                        labelsubt.setText("Hi " + dataF1.getNombre1());
                        jMenu1.setVisible(true);
                        jMenu2.setVisible(true);
                        jMenu3.setVisible(true);
                        jMenu4.setVisible(true);
                        jMenu5.setVisible(true);
                        jMenu6.setVisible(true);
                        jMenuItem15.setVisible(true);
                        jMenuItem8.setVisible(false);
                        jMenuItem12.setVisible(false);
                        jMenuBar1.setVisible(true);
                        jdp2.setVisible(false);
                        jdp3.setVisible(false);
                        btnCerrar.setVisible(false);
                        labeltitulo.setVisible(true);
                        labelsubt.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrecta!");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (txtTipo.getSelectedItem() == "Usuario") {

                Jdbc cx = new Jdbc();
                UsuarioJdbc ujdbc = new UsuarioJdbc();
                try {
                    cx.conectarme();
                    ujdbc.setCon(cx.getCon());

                    char[] arrayC = txtPassword.getPassword();
                    String pass = new String(arrayC);
                    dataU1 = ujdbc.Login(txtUsuario.getText().trim(), pass);

                    if (dataU1.getIdentificacion() != null) {
                        txtUsuario.setText("");
                        txtPassword.setText("");

                        JOptionPane.showMessageDialog(null, "Bienvenido/a " + dataU1.getNombre1() + " " + dataU1.getApellido1());
                        jMenu6.setText(dataU1.getNombre1() + " " + dataU1.getApellido1());
                        labelsubt.setText("Hi " + dataU1.getNombre1());
                        jMenuBar1.setVisible(true);
                        jMenu1.setVisible(false);
                        jMenu4.setVisible(true);
                        jMenu6.setVisible(true);
                        jMenuItem9.setVisible(false);
                        jMenuItem10.setVisible(false);
                        jMenuItem15.setVisible(false);
                        jMenuItem8.setVisible(true);
                        jMenuItem12.setVisible(true);

                        jMenu2.setVisible(false);
                        jMenu3.setVisible(true);
                        jMenu5.setVisible(true);

                        jdp2.setVisible(false);
                        jdp3.setVisible(false);
                        btnCerrar.setVisible(false);
                        labeltitulo.setVisible(true);
                        labelsubt.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrecta!");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        
        
    }//GEN-LAST:event_btnIniciarSecionActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        labeltitulo.setVisible(false);
        labelsubt.setVisible(false);
        
        GUI_ListarPrestamos cf = new GUI_ListarPrestamos();
        jdp.add(cf);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = cf.getSize();
        cf.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        GUI_ListarPrestamos lp = new GUI_ListarPrestamos();        
        jdp.add(lp);
        lp.usuarioId = dataU1.getIdentificacion();
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = lp.getSize();
        lp.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        lp.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        GUI_DevolucionPrestamo dp = new GUI_DevolucionPrestamo();        
        jdp.add(dp);
        //Centra en JInternalFrame
        Dimension desktopSize = jdp.getSize();
        Dimension FrameSize = dp.getSize();
        dp.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        //
        dp.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIniciarSecion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JDesktopPane jdp;
    private javax.swing.JDesktopPane jdp2;
    private javax.swing.JDesktopPane jdp3;
    public javax.swing.JLabel labelsubt;
    public javax.swing.JLabel labeltitulo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JComboBox<String> txtTipo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
