/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.usuario;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import jdbc.Jdbc;
import jdbc.UsuarioJdbc;
import modelo.Usuario;
import vistas.Fondo;

/**
 *
 * @author Usuario
 */
public class GUI_Crear_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_Crear_Usuario
     */
    public GUI_Crear_Usuario() {
        initComponents();
        
        groupSexoBtn.add(rBtn1);
        groupSexoBtn.add(rBtn2);
        
        groupInscritoBtn.add(rBtnInscrito1);
        groupInscritoBtn.add(rBtnInscrito2);
        
        groupControlPagoBtn.add(rBtncontrol1);
        groupControlPagoBtn.add(rBtncontrol2);
                        cargarImagen(jdp4,foto1);
        ocultarBarraTitulo();
        
    }
    
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
private Dimension dimBarra = null; 
public void ocultarBarraTitulo()
{ 
Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
dimBarra = Barra.getPreferredSize(); 
Barra.setSize(0,0); 
Barra.setPreferredSize(new Dimension(0,0)); 
repaint(); 
}
  public InputStream foto1=this.getClass().getResourceAsStream("/imagenes/bl.jpg");
            public  void cargarImagen(javax.swing.JDesktopPane jDeskp,InputStream fileImagen)
    {   
        try{   
            BufferedImage image = ImageIO.read(fileImagen);        
              jDeskp.setBorder(new Fondo(image)); }
        catch (Exception e){   System.out.println("Imagen no disponible");   }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSexoBtn = new javax.swing.ButtonGroup();
        groupInscritoBtn = new javax.swing.ButtonGroup();
        groupControlPagoBtn = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrarUsuario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCerrarVistaCrearUsuario = new javax.swing.JButton();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jdp4 = new javax.swing.JDesktopPane();
        rBtn2 = new javax.swing.JRadioButton();
        txtPagoAnual = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        rBtncontrol1 = new javax.swing.JRadioButton();
        rBtncontrol2 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCodigoInst = new javax.swing.JTextField();
        rBtnInscrito2 = new javax.swing.JRadioButton();
        rBtnInscrito1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txtTipoUsu = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        rBtn1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setTitle("Crear Usuario");
        setMinimumSize(new java.awt.Dimension(854, 540));
        setPreferredSize(new java.awt.Dimension(854, 540));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Identificacion: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 130, 17);

        jLabel11.setBackground(new java.awt.Color(0, 204, 204));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Contraseña:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(480, 350, 130, 17);

        btnRegistrarUsuario.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarUsuario.setText("REGISTRAR");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUsuario);
        btnRegistrarUsuario.setBounds(310, 440, 150, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Primer Nombre: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 100, 140, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Segundo Nombre: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 140, 150, 17);

        btnCerrarVistaCrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarVistaCrearUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCerrarVistaCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarVistaCrearUsuario.setText("VOLVER");
        btnCerrarVistaCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarVistaCrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarVistaCrearUsuario);
        btnCerrarVistaCrearUsuario.setBounds(490, 440, 110, 30);

        txtIdentificacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIdentificacion.setName("txtIdentificacionF"); // NOI18N
        getContentPane().add(txtIdentificacion);
        txtIdentificacion.setBounds(190, 60, 178, 23);

        txtNombre1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombre1.setName("txtPrimerNombreF"); // NOI18N
        getContentPane().add(txtNombre1);
        txtNombre1.setBounds(190, 100, 178, 23);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtPassword);
        txtPassword.setBounds(630, 340, 178, 23);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("CREAR USUARIO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 0, 180, 50);
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(-1, -1, 0, 0);

        jdp4.setBackground(new java.awt.Color(255, 255, 255));

        rBtn2.setText("Femenino");
        jdp4.add(rBtn2);
        rBtn2.setBounds(310, 340, 80, 23);

        txtPagoAnual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jdp4.add(txtPagoAnual);
        txtPagoAnual.setBounds(650, 260, 178, 23);

        txtTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jdp4.add(txtTelefono);
        txtTelefono.setBounds(650, 340, 178, 23);

        jLabel10.setBackground(new java.awt.Color(0, 204, 204));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Telefono: ");
        jdp4.add(jLabel10);
        jLabel10.setBounds(500, 350, 80, 17);

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Correo Electronico: ");
        jdp4.add(jLabel7);
        jLabel7.setBounds(500, 300, 130, 17);

        txtCorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jdp4.add(txtCorreo);
        txtCorreo.setBounds(650, 300, 178, 23);

        rBtncontrol1.setText("Si");
        rBtncontrol1.setName("rbtnSi"); // NOI18N
        jdp4.add(rBtncontrol1);
        rBtncontrol1.setBounds(650, 220, 80, 23);

        rBtncontrol2.setText("No");
        rBtncontrol2.setName("rbtnNo"); // NOI18N
        jdp4.add(rBtncontrol2);
        rBtncontrol2.setBounds(750, 220, 80, 23);

        jLabel18.setBackground(new java.awt.Color(0, 204, 204));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Pago Anual:");
        jdp4.add(jLabel18);
        jLabel18.setBounds(500, 260, 130, 17);

        jLabel17.setBackground(new java.awt.Color(0, 204, 204));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Pagó:");
        jdp4.add(jLabel17);
        jLabel17.setBounds(500, 220, 140, 20);

        jLabel16.setBackground(new java.awt.Color(0, 204, 204));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Codigo Institucional: ");
        jdp4.add(jLabel16);
        jLabel16.setBounds(500, 180, 140, 17);

        txtCodigoInst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jdp4.add(txtCodigoInst);
        txtCodigoInst.setBounds(650, 180, 178, 23);

        rBtnInscrito2.setText("No");
        rBtnInscrito2.setName("rbtnNo"); // NOI18N
        jdp4.add(rBtnInscrito2);
        rBtnInscrito2.setBounds(760, 140, 80, 23);

        rBtnInscrito1.setText("Si");
        rBtnInscrito1.setName("rbtnSi"); // NOI18N
        jdp4.add(rBtnInscrito1);
        rBtnInscrito1.setBounds(650, 140, 80, 23);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Inscrito: ");
        jdp4.add(jLabel14);
        jLabel14.setBounds(500, 150, 100, 17);

        txtTipoUsu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante Colombo", "Estudiante Exterior", "Estudiante Unicolombo", "Profesor", " " }));
        jdp4.add(txtTipoUsu);
        txtTipoUsu.setBounds(210, 380, 178, 23);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Tipo De Usuario: ");
        jdp4.add(jLabel13);
        jLabel13.setBounds(60, 380, 140, 17);

        rBtn1.setText("Masculino");
        jdp4.add(rBtn1);
        rBtn1.setBounds(210, 340, 90, 23);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Sexo: ");
        jdp4.add(jLabel8);
        jLabel8.setBounds(60, 340, 90, 20);
        jdp4.add(txtFechaNacimiento);
        txtFechaNacimiento.setBounds(210, 300, 180, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Fecha De Nacimiento: ");
        jdp4.add(jLabel6);
        jLabel6.setBounds(60, 310, 170, 17);

        txtApellido2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtApellido2.setName("txtSegundoApellidoF"); // NOI18N
        jdp4.add(txtApellido2);
        txtApellido2.setBounds(210, 260, 178, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Segundo Apellido: ");
        jdp4.add(jLabel2);
        jLabel2.setBounds(60, 270, 150, 17);

        txtApellido1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtApellido1.setName("txtPrimerApellidoF"); // NOI18N
        jdp4.add(txtApellido1);
        txtApellido1.setBounds(210, 220, 178, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Primer Apellido: ");
        jdp4.add(jLabel3);
        jLabel3.setBounds(60, 230, 140, 17);

        txtNombre2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombre2.setName("txtSegundoNombreF"); // NOI18N
        jdp4.add(txtNombre2);
        txtNombre2.setBounds(210, 180, 178, 23);

        getContentPane().add(jdp4);
        jdp4.setBounds(-20, -40, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        
        String sexo = "";
        boolean inscrito = false;
        boolean controlPago = false;
        
        if (rBtn1.isSelected()) {
            sexo = "Masculino";
        } else if (rBtn2.isSelected()) {
            sexo = "Femenido";
        }
        
        if (rBtnInscrito1.isSelected()) {
            inscrito = true;
        } else if (rBtnInscrito2.isSelected()) {
            inscrito = false;
        }
        
        if (rBtncontrol1.isSelected()) {
            controlPago = true;
        } else if (rBtncontrol2.isSelected()) {
            controlPago = false;
        }

        char[] arrayC = txtPassword.getPassword();
        String pass = new String(arrayC);
        
        Usuario u1 = new Usuario();
        u1.setApellido1(txtApellido1.getText().trim());
        u1.setApellido2(txtApellido2.getText().trim());
        u1.setCorreo(txtCorreo.getText().trim());
        u1.setFechaNacimiento(txtFechaNacimiento.getDate());
        u1.setIdentificacion(txtIdentificacion.getText().trim());
        u1.setNombre1(txtNombre1.getText().trim());
        u1.setNombre2(txtNombre2.getText().trim());
        u1.setPassword(pass);
        u1.setSexo(sexo);
        u1.setTelefono(txtTelefono.getText().trim());        
        u1.setCodigoInstitucional(txtCodigoInst.getText().trim());
        u1.setControlPago(controlPago);
        u1.setInscrito(inscrito);
        u1.setPagoAnual(Double.parseDouble(txtPagoAnual.getText().trim()));
        u1.setTipoUsuario(pass);
        
        Jdbc cx = new Jdbc();
        UsuarioJdbc fjdbc = new UsuarioJdbc();
        try {
            cx.conectarme();
            fjdbc.setCon(cx.getCon());
            fjdbc.saveUsuario(u1);

        } catch (SQLException ex) {
            Logger.getLogger(GUI_Crear_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnCerrarVistaCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarVistaCrearUsuarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarVistaCrearUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarVistaCrearUsuario;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.ButtonGroup groupControlPagoBtn;
    private javax.swing.ButtonGroup groupInscritoBtn;
    private javax.swing.ButtonGroup groupSexoBtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDesktopPane jdp4;
    private javax.swing.JRadioButton rBtn1;
    private javax.swing.JRadioButton rBtn2;
    private javax.swing.JRadioButton rBtnInscrito1;
    private javax.swing.JRadioButton rBtnInscrito2;
    private javax.swing.JRadioButton rBtncontrol1;
    private javax.swing.JRadioButton rBtncontrol2;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCodigoInst;
    private javax.swing.JTextField txtCorreo;
    private com.toedter.calendar.JDateChooser txtFechaNacimiento;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtPagoAnual;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JComboBox<String> txtTipoUsu;
    // End of variables declaration//GEN-END:variables
}
